### ISSUE TITLE
Plugin.audio.ytmusic.exp-1.0~beta10 - No Tracks Found

### ISSUE THREAD

**Issue by AndrRap** [Goldenfreddy0703/plugin.audio.ytmusic.exp#15]
Installed on RPi3 with LE 10.0.3 and Kodi 19.4.
Header is fine but any selection gives: "No Tracks Found".
Logs is here: https://paste.kodi.tv/egekiguvat.kodi 
Thanks for any help

**Comment by Goldenfreddy0703** [comment]
Hey so sorry for no responding but this addon is kinda dead and idk how to fix it. I don't have any contributors to help maintain and work on this addon sadly. I wish we had more but no one is interested in YTMusic Sadly.

**Comment by woernsn** [comment]
I don't see anything helpful in the logs.
Also I retested beta 10 with Kodi 19.3 and 19.4 right now and everything is working as expected.
Are you sure, you authenticated correctly?
Try to invalid authentication cache and re-sign in.

**Comment by kudlav** [comment]
I have problem with initial sync as well. Obtained new credentials but still crashing during the sync:

```log
2022-11-23 13:57:05.783 T:1402     INFO <general>: initializing python engine.
2022-11-23 13:57:05.997 T:1402     INFO <general>: [YtMusicEXP-1.0~beta12]  ARGV: ['plugin://plugin.audio.ytmusic.exp/', '23', '?path=playlist&playlist_id=thumbsup', 'resume:false']
2022-11-23 13:57:06.019 T:1402     INFO <general>: [YtMusicEXP-1.0~beta12] #1# INIT STARTED :'0' - FETCHED TIME: 0
2022-11-23 13:57:06.019 T:1402     INFO <general>: [YtMusicEXP-1.0~beta12] Initing addon data
2022-11-23 13:57:07.293 T:1402     INFO <general>: [YtMusicEXP-1.0~beta12] Loading auth from cache
2022-11-23 13:57:08.611 T:1402     INFO <general>: Skipped 1 duplicate messages..
2022-11-23 13:57:08.611 T:1402     INFO <general>: [YtMusicEXP-1.0~beta12] PATH: playlist
2022-11-23 13:57:08.611 T:1402     INFO <general>: [YtMusicEXP-1.0~beta12] Loading playlist: thumbsup
2022-11-23 13:57:08.611 T:1402     INFO <general>: [YtMusicEXP-1.0~beta12] Loading auth from cache
2022-11-23 13:57:19.233 T:1402     INFO <general>: Skipped 1 duplicate messages..
2022-11-23 13:57:19.233 T:1402     INFO <general>: [YtMusicEXP-1.0~beta12] Unexpected error:<class 'Exception'>
2022-11-23 13:57:19.250 T:1402    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'Exception'>
                                                   Error Contents: Server returned HTTP 500: Internal Server Error.
                                                   Internal error encountered.
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.audio.ytmusic.exp/resources/lib/addon.py", line 118, in <module>
                                                       Api().load_playlists()
                                                     File "/storage/.kodi/addons/plugin.audio.ytmusic.exp/resources/lib/api.py", line 46, in load_playlists
                                                       playlists = self.getApi().get_library_playlists(100)
                                                     File "/storage/.kodi/addons/plugin.audio.ytmusic.exp/resources/lib/ytmusicapi/mixins/library.py", line 39, in get_library_playlists
                                                       get_continuations(results, 'gridContinuation', limit - len(playlists),
                                                     File "/storage/.kodi/addons/plugin.audio.ytmusic.exp/resources/lib/ytmusicapi/parsers/utils.py", line 59, in get_continuations
                                                       response = request_func(additionalParams)
                                                     File "/storage/.kodi/addons/plugin.audio.ytmusic.exp/resources/lib/ytmusicapi/mixins/library.py", line 35, in <lambda>
                                                       request_func = lambda additionalParams: self._send_request(
                                                     File "/storage/.kodi/addons/plugin.audio.ytmusic.exp/resources/lib/ytmusicapi/ytmusic.py", line 142, in _send_request
                                                       raise Exception(message + error)
                                                   Exception: Server returned HTTP 500: Internal Server Error.
                                                   Internal error encountered.
                                                   -->End of Python script error report<--
                                                   
2022-11-23 13:57:19.862 T:1402     INFO <general>: Python interpreter stopped
```

**Comment by doucettom** [comment]
I have the same problem. LibreELEC 10.0.3 on x86_64 YTmusic 1.0beta12

2023-01-14 00:04:22.549 T:1238     INFO <general>: initializing python engine.
2023-01-14 00:04:22.604 T:1238     INFO <general>: [YtMusicEXP-1.0~beta12]  ARGV: ['plugin://plugin.audio.ytmusic.exp/', '-1', '?action=clear_cache', 'resume:false']
2023-01-14 00:04:22.608 T:1238     INFO <general>: [YtMusicEXP-1.0~beta12] #1# INIT STARTED :'0' - FETCHED TIME: 0
2023-01-14 00:04:22.608 T:1238     INFO <general>: [YtMusicEXP-1.0~beta12] Initing addon data
2023-01-14 00:04:22.783 T:1097     INFO <general>: Loading skin file: DialogSelect.xml, load type: KEEP_IN_MEMORY
2023-01-14 00:04:31.175 T:1097     INFO <general>: Loading skin file: FileBrowser.xml, load type: KEEP_IN_MEMORY
2023-01-14 00:04:39.084 T:1238     INFO <general>: [YtMusicEXP-1.0~beta12] YTMUSIC Unexpected error:<class 'TypeError'>
2023-01-14 00:04:39.358 T:1238     INFO <general>: [YtMusicEXP-1.0~beta12] UPLOADS Unexpected error:<class 'KeyError'>
2023-01-14 00:04:39.440 T:1238     INFO <general>: [YtMusicEXP-1.0~beta12] No tracks found
2023-01-14 00:04:39.441 T:1238     INFO <general>: [YtMusicEXP-1.0~beta12] Clearing cache...
2023-01-14 00:04:39.483 T:1238     INFO <general>: CPythonInvoker(19, /storage/.kodi/addons/plugin.audio.ytmusic.exp/resources/lib/addon.py): script successfully run
2023-01-14 00:04:39.687 T:1238     INFO <general>: Python interpreter stopped
